### ISSUE TITLE
Skill load error

### ISSUE THREAD

**Issue by jackgrahamhindley** [guhl/wake-button-rpi-skill#1]
I get the following in message bus:
mycroft.skills.skill_loader:_create_skill_instance:289 | Skill initialization failed with AttributeError("module 'RPi.GPIO' has no attribute 'error'")
... and ...
mycroft.skills.skill_loader:_communicate_load_status:327 | Skill wake-button-rpi-skill.guhl failed to load

Is it something you can easily update in the __init__.py file?

Sorry, more error from the same instance:

Traceback (most recent call last):
  File "/opt/mycroft/skills/wake-button-rpi-skill.guhl/__init__.py", line 18, in initialize
    GPIO.add_event_detect(BUTTON, GPIO.RISING, bouncetime = 500)
RuntimeError: Failed to add edge detection

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/skill_loader.py", line 283, in _create_skill_instance
    self.instance.initialize()
  File "/opt/mycroft/skills/wake-button-rpi-skill.guhl/__init__.py", line 19, in initialize
    except GPIO.error:
AttributeError: module 'RPi.GPIO' has no attribute 'error'

**Comment by guhl** [comment]
Can you please tell me which version of the RPi.GPIO python module is installed?
You should be able to find this by running the command mycroft-pip list on your device.

**Comment by jackgrahamhindley** [comment]
Thanks for getting back. I'm on 0.7.0 with RPi.GPIO.

**Comment by guhl** [comment]
I could finally reproduce that error by setting up a new installation.
Did you read and follow the section in the README Important - Access to GPIO device
I had the same errors before I installed the 99-com.rules, added the gpio group and added the mycroft user to the gpio group.

Rather misleading error messages.
 
Can you check that?
